# PROMPT FOR NOVICE LLM:
# Write a Python script that checks for mismatches between component IDs and their descriptions in the Components sheet of the ivntest.xlsx Excel file.
# Prompt the user at the beginning: "Normalize the dataset before using this script. This script uses the Components sheet of normalized components generated by another script, NOT the open-text Dataset sheet. Would you like to quit now and return to this script after normalizing the data?"
# Prompt the user for a similarity threshold (float between 0 and 1) to filter similarity results.
# If the user chooses to continue, find cases where a component_id maps to more than one component_description (including mismatches between null and non-null values, and treating different capitalization as different descriptions).
# Also find cases where a component_description maps to more than one component_id (including mismatches between null and non-null values, and treating different capitalization as different descriptions).
# For every possible pair of components, compute a "component similarity score" using the cosine similarity of their names and export only pairs with a score at or above the threshold to a "Component Similarity" sheet.
# For every possible pair of descriptions, compute a "description similarity score" using the cosine similarity of their text and export only pairs with a score at or above the threshold to a "Description Similarity" sheet. For each description, include the component_id and component_name that description describes.
# Add the "component similarity score" column to the one_component_many_descriptions sheet and the "description similarity score" column to the one_description_many_components sheet.
# Export all mismatches into separate sheets named "one_component_many_descriptions" and "one_description_many_components" in an output file named component_description_mismatches-YYYY-MM-DD-HHMM.xlsx, where the timestamp is the current date and time.
# Do not change the case of the output text; preserve the original case from the input file.
# Do not strip whitespace from the strings.
# Print the columns found in the Components sheet for debugging.
# After exporting, print a general instruction for how to edit the production dataset based on the output.
# Estimate and print elapsed and remaining time for the script, especially for similarity calculations.
# Update this prompt every time you update the script.

# Last updated: 2025-09-10

import pandas as pd
from datetime import datetime
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import time

start_time = time.time()

# Prompt user to confirm normalization
response = input(
    "Normalize the dataset before using this script. This script uses the Components sheet of normalized components generated by another script, NOT the open-text Dataset sheet.\n"
    "Would you like to quit now and return to this script after normalizing the data? (y/n): "
)
if response.strip().lower() == "y":
    print("Quitting script. Please normalize your data and run this script again.")
    exit()

# Prompt user for similarity threshold
while True:
    try:
        threshold = float(input("Enter similarity threshold (0 to 1, e.g. 0.8): "))
        if 0 <= threshold <= 1:
            break
        else:
            print("Please enter a value between 0 and 1.")
    except ValueError:
        print("Please enter a numeric value between 0 and 1.")

sheet_name = "Components"
df = pd.read_excel("ivntest.xlsx", sheet_name=sheet_name)
print(f"Columns in '{sheet_name}': {list(df.columns)}")

# Estimate steps for timing
total_steps = 4
step = 1

def print_time_estimate(step, total_steps, start_time):
    elapsed = time.time() - start_time
    avg_per_step = elapsed / step
    remaining = avg_per_step * (total_steps - step)
    print(f"Step {step}/{total_steps} complete. Elapsed: {elapsed:.2f}s. Estimated remaining: {remaining:.2f}s.")

# 1) Components with more than one description (including null/non-null mismatches)
one_component_many_descriptions = pd.DataFrame()
if "component_id" in df.columns and "component_description" in df.columns:
    grouped = df.groupby("component_id")["component_description"].apply(lambda x: x.nunique(dropna=False))
    mismatched_keys = grouped[grouped > 1].index
    one_component_many_descriptions = df[df["component_id"].isin(mismatched_keys)].copy()
    if not one_component_many_descriptions.empty:
        one_component_many_descriptions["Mismatch Type"] = "One Component, Many Descriptions"
        component_names = one_component_many_descriptions["component_name"].fillna("").astype(str).tolist()
        vectorizer = TfidfVectorizer().fit(component_names)
        tfidf_matrix = vectorizer.transform(component_names)
        cosine_matrix = cosine_similarity(tfidf_matrix)
        similarity_scores = []
        for i in range(len(component_names)):
            scores = cosine_matrix[i]
            max_score = max([score for j, score in enumerate(scores) if j != i], default=0)
            similarity_scores.append(max_score)
        one_component_many_descriptions["component similarity score"] = similarity_scores
print_time_estimate(step, total_steps, start_time)
step += 1

# 2) Descriptions shared by multiple components (including null/non-null mismatches)
one_description_many_components = pd.DataFrame()
if "component_id" in df.columns and "component_description" in df.columns:
    grouped_desc = df.groupby("component_description")["component_id"].apply(lambda x: x.nunique(dropna=False))
    shared_desc_keys = grouped_desc[grouped_desc > 1].index
    one_description_many_components = df[df["component_description"].isin(shared_desc_keys)].copy()
    if not one_description_many_components.empty:
        one_description_many_components["Mismatch Type"] = "One Description, Many Components"
        descriptions = one_description_many_components["component_description"].fillna("").astype(str).tolist()
        vectorizer_desc = TfidfVectorizer().fit(descriptions)
        tfidf_matrix_desc = vectorizer_desc.transform(descriptions)
        cosine_matrix_desc = cosine_similarity(tfidf_matrix_desc)
        similarity_scores_desc = []
        for i in range(len(descriptions)):
            scores = cosine_matrix_desc[i]
            max_score = max([score for j, score in enumerate(scores) if j != i], default=0)
            similarity_scores_desc.append(max_score)
        one_description_many_components["description similarity score"] = similarity_scores_desc
print_time_estimate(step, total_steps, start_time)
step += 1

# If no mismatches, create empty DataFrames with a message
if one_component_many_descriptions.empty:
    one_component_many_descriptions = pd.DataFrame({"No mismatches found": []})
if one_description_many_components.empty:
    one_description_many_components = pd.DataFrame({"No mismatches found": []})

# 3) Component Similarity sheet: cosine similarity for every possible pair of unique components (i < j)
component_similarity_df = pd.DataFrame()
if "component_name" in df.columns:
    component_names_all = df["component_name"].fillna("").astype(str).unique().tolist()
    vectorizer_all = TfidfVectorizer().fit(component_names_all)
    tfidf_matrix_all = vectorizer_all.transform(component_names_all)
    cosine_matrix_all = cosine_similarity(tfidf_matrix_all)
    pairs = []
    n = len(component_names_all)
    print(f"Calculating component similarity for {n*(n-1)//2} pairs...")
    sim_start = time.time()
    for i in range(n):
        for j in range(i+1, n):
            score = cosine_matrix_all[i, j]
            if score >= threshold:
                pairs.append({
                    "component_name_1": component_names_all[i],
                    "component_name_2": component_names_all[j],
                    "component similarity score": score
                })
        if (i+1) % 100 == 0 or i == n-1:
            elapsed = time.time() - sim_start
            est_total = elapsed / (i+1) * n
            est_remaining = est_total - elapsed
            print(f"Component similarity: {i+1}/{n} done. Elapsed: {elapsed:.2f}s. Estimated remaining: {est_remaining:.2f}s.")
    component_similarity_df = pd.DataFrame(pairs)
print_time_estimate(step, total_steps, start_time)
step += 1

# 4) Description Similarity sheet: cosine similarity for every possible pair of unique descriptions (i < j)
description_similarity_df = pd.DataFrame()
if "component_description" in df.columns:
    descriptions_all = df["component_description"].fillna("").astype(str).unique().tolist()
    # Map each description to its first component_id and component_name in the dataset
    desc_to_comp = df.drop_duplicates(subset=["component_description"])[["component_description", "component_id", "component_name"]].set_index("component_description")
    vectorizer_desc_all = TfidfVectorizer().fit(descriptions_all)
    tfidf_matrix_desc_all = vectorizer_desc_all.transform(descriptions_all)
    cosine_matrix_desc_all = cosine_similarity(tfidf_matrix_desc_all)
    desc_pairs = []
    n_desc = len(descriptions_all)
    print(f"Calculating description similarity for {n_desc*(n_desc-1)//2} pairs...")
    sim_start = time.time()
    for i in range(n_desc):
        for j in range(i+1, n_desc):
            score = cosine_matrix_desc_all[i, j]
            if score >= threshold:
                desc1 = descriptions_all[i]
                desc2 = descriptions_all[j]
                desc_pairs.append({
                    "component_description_1": desc1,
                    "component_id_1": desc_to_comp.loc[desc1, "component_id"] if desc1 in desc_to_comp.index else None,
                    "component_name_1": desc_to_comp.loc[desc1, "component_name"] if desc1 in desc_to_comp.index else None,
                    "component_description_2": desc2,
                    "component_id_2": desc_to_comp.loc[desc2, "component_id"] if desc2 in desc_to_comp.index else None,
                    "component_name_2": desc_to_comp.loc[desc2, "component_name"] if desc2 in desc_to_comp.index else None,
                    "description similarity score": score
                })
        if (i+1) % 100 == 0 or i == n_desc-1:
            elapsed = time.time() - sim_start
            est_total = elapsed / (i+1) * n_desc
            est_remaining = est_total - elapsed
            print(f"Description similarity: {i+1}/{n_desc} done. Elapsed: {elapsed:.2f}s. Estimated remaining: {est_remaining:.2f}s.")
    description_similarity_df = pd.DataFrame(desc_pairs)
print_time_estimate(step, total_steps, start_time)

# Generate timestamp for filename
timestamp = datetime.now().strftime("%Y-%m-%d-%H%M")
output_filename = f"component_description_mismatches-{timestamp}.xlsx"

with pd.ExcelWriter(output_filename, engine="openpyxl") as writer:
    one_component_many_descriptions.to_excel(writer, sheet_name="one_component_many_descriptions", index=False)
    one_description_many_components.to_excel(writer, sheet_name="one_description_many_components", index=False)
    component_similarity_df.to_excel(writer, sheet_name="Component Similarity", index=False)
    description_similarity_df.to_excel(writer, sheet_name="Description Similarity", index=False)

total_elapsed = time.time() - start_time
print(f"Total elapsed time: {total_elapsed:.2f}s")
print("Instruction: For each mismatch in 'one_component_many_descriptions', standardize the component_description so that each component_id maps to only one unique description in the production dataset (including handling nulls and case differences as mismatches).")
print("Instruction: For each mismatch in 'one_description_many_components', ensure that each component_description is only used for one component_id in the production dataset (including handling nulls and case differences as mismatches).")
print("Instruction: Use the 'Component Similarity' and 'Description Similarity' sheets to identify similar components and descriptions that may need normalization or merging.")
print(f"Mismatch export complete: {output_filename}")
